package id.devtools.browser.network

/**
 * One captured HTTP request/response observed in a tab.
 *
 * Two capture lanes feed this model (see NetworkCapture):
 * - NATIVE: [android.webkit.WebViewClient.shouldInterceptRequest] records the
 *   request skeleton (URL, method, headers). It never refetches the request.
 * - JS: injected fetch/XHR wrappers report method, URL, status, headers and
 *   (text) bodies through the JS bridge.
 */
data class NetworkEntry(
    val id: Long,
    val tabId: String,
    val url: String,
    val method: String,
    val resourceType: NetworkResourceType,
    val startTimeMs: Long = System.currentTimeMillis(),
    val endTimeMs: Long? = null,
    val statusCode: Int? = null,
    val requestHeaders: Map<String, String> = emptyMap(),
    val responseHeaders: Map<String, String> = emptyMap(),
    val requestBody: String? = null,
    val responseBody: String? = null,
    val error: String? = null,
    val source: NetworkSource = NetworkSource.NATIVE,
    /** Id generated by the injected JS wrapper; used to correlate events. */
    val clientId: String? = null,
)

enum class NetworkResourceType {
    DOCUMENT,
    XHR,
    SCRIPT,
    STYLESHEET,
    IMAGE,
    MEDIA,
    FONT,
    OTHER,
}

enum class NetworkSource {
    /** Seen only by shouldInterceptRequest (no status/body). */
    NATIVE,
    /** Seen only by the injected fetch/XHR wrapper. */
    JS,
    /** Observed by both lanes and deduplicated into one entry. */
    MERGED,
}

/**
 * Infers the resource type from the URL. The native lane has no content-type
 * at intercept time, so the extension is the best available signal.
 */
fun guessResourceType(url: String, isMainFrame: Boolean): NetworkResourceType {
    if (isMainFrame) return NetworkResourceType.DOCUMENT
    val path = url.substringBefore('?').substringBefore('#').lowercase()
    return when (path.substringAfterLast('.', "")) {
        "js", "mjs" -> NetworkResourceType.SCRIPT
        "css" -> NetworkResourceType.STYLESHEET
        "png", "jpg", "jpeg", "gif", "webp", "svg", "ico", "bmp", "avif" ->
            NetworkResourceType.IMAGE
        "mp4", "webm", "mp3", "ogg", "wav", "m4a" -> NetworkResourceType.MEDIA
        "woff", "woff2", "ttf", "otf", "eot" -> NetworkResourceType.FONT
        "json" -> NetworkResourceType.XHR
        else -> NetworkResourceType.OTHER
    }
}
